class: rails
dependencies:
  hard: {}
  soft: {}
nagios:
  check: true
  notify: false
proxy: 
  host: rmd-test.dlib.indiana.edu
  path: /
system:
  autostart: true
  environment: test
  group: service_rails_admins
  name: rmd
  path: /srv/services/rmd-test-8151
  port: 8151
  runtime: default
  user: app_rmd
