class: rails
dependencies:
  hard: {}
  soft: {}
nagios:
  check: true
  notify: true
proxy: 
  host: rmd-dev.dlib.indiana.edu
  path: /
system:
  autostart: false
  environment: devel
  group: service_rails_admins
  name: rmd
  path: /srv/services/rmd-devel-8146
  port: 8146
  runtime: default
  user: app_rmd
