development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= Rails.configuration.rmd[:db_name] %>
  username: <%= Rails.configuration.rmd[:username] %>
  password: <%= Rails.configuration.rmd[:password] %>
  host: <%= Rails.configuration.rmd[:host] %>

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= Rails.configuration.rmd[:db_name] %>
  username: <%= Rails.configuration.rmd[:username] %>
  password: <%= Rails.configuration.rmd[:password] %>
  host: <%= Rails.configuration.rmd[:host] %>
