# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

test:
  secret_key_base: 4eff42e5c874204aaef9534a6e3021a9cd3ae7ff5e300b7373296d3510a3a47c3323e2933bfe70dad3a0d8c58b2db7b949337afd269ab791ce9617d0b99fb5cf
  old_avalon_token: d464fc76b36b64091ac6ba345850e702e68635c0ecb515f2692aa946d415ffb238e442b049c31c8d370e22d8183490ed14f8a9e391a99e3ee9831c21b915e999​
  avalon_token: c6395972c556953bb5683fd53ed72f7dce4b305a425737be90845d25a6adf2e01c2b7c0b9de0e9852bcaf491a358f7317fce5d18f0ba553077868703e27b4688
  # use mco staging for now
  avalon_url: https://mco-staging.dlib.indiana.edu/catalog.atom?q=other_identifier_sim:<identifier>&sort=timestamp+<order>&rows=<row_count>&page=<page_count>
  avalon_media_url: 'https://mco-staging.dlib.indiana.edu/media_objects/:id'
  db_name: app_rmd_test
  username: app_rmd
  password: Moroccos@nun>envenomed333
  host: dragon.dlib.indiana.edu

  service_username: cabbage_soup
  service_password: impossibly^Reconditioned
  ldap_host: ads.iu.edu
  ldap_username: dlptech
  ldap_password: 'Non-condensing lemon'

  pod_full_metadata_url: https://pod.mdpi.iu.edu/responses/objects/:mdpi_barocde/metadata/full
  pod_bauth_username: akaBodySnatchers
  pod_bauth_password: remake1978


